# Generates the AVX-VNNI micro-kernel:
#
#     python3 gen_vnni.py > kernel_vnni_amd64.s
#
# The Go assembler only encodes VPDPBUSD as EVEX (AVX-512); the VEX form
# of AVX-VNNI is therefore written byte by byte.


def vpdpbusd(acc, a, b):
    # acc += a (uint8, vvvv field) . b (int8, r/m field): VEX.256.66.0F38.W0 50 /r
    R = 0 if acc >= 8 else 1
    B = 0 if b >= 8 else 1
    b1 = (R << 7) | (1 << 6) | (B << 5) | 0x02
    b2 = (((~a) & 0xF) << 3) | (1 << 2) | 0x01
    modrm = 0xC0 | ((acc & 7) << 3) | (b & 7)
    bs = [0xC4, b1, b2, 0x50, modrm]
    return "\tBYTE $0x%02X; BYTE $0x%02X; BYTE $0x%02X; BYTE $0x%02X; BYTE $0x%02X // VPDPBUSD Y%d, Y%d, Y%d" % (*bs, b, a, acc)


out = ['''// Code generated by gen_vnni.py; DO NOT EDIT.

#include "textflag.h"

// func microKernelVNNI(kq int, ap *uint8, lda int, bp *int8, tile *int32)
//
// 6x16 integer tile: Y0..Y11 accumulate C (row r in Y(2r), Y(2r+1)),
// Y12 and Y13 carry 16 columns x 4 depths of B (int8), Y14 and Y15
// broadcast 4 bytes of an A row (uint8). The 6 rows of A are contiguous,
// spaced lda bytes apart: SI points at rows 0 to 2, R9 at rows 3 to 5.
// VPDPBUSD sums the four products of each column into its int32
// accumulator.
TEXT ·microKernelVNNI(SB), NOSPLIT, $0-40
	MOVQ kq+0(FP), CX
	MOVQ ap+8(FP), SI
	MOVQ lda+16(FP), R8
	MOVQ bp+24(FP), DI
	MOVQ tile+32(FP), DX
	LEAQ (SI)(R8*2), R9
	ADDQ R8, R9
''']
for r in range(12):
    out.append("\tVPXOR Y%d, Y%d, Y%d" % (r, r, r))
out.append('''
	TESTQ CX, CX
	JEQ   store

loop:
	VMOVDQU (DI), Y12
	VMOVDQU 32(DI), Y13''')
addr = ["(SI)", "(SI)(R8*1)", "(SI)(R8*2)", "(R9)", "(R9)(R8*1)", "(R9)(R8*2)"]
for r in range(6):
    reg = 14 + (r % 2)
    out.append("\tVPBROADCASTD %s, Y%d" % (addr[r], reg))
    out.append(vpdpbusd(2 * r, reg, 12))
    out.append(vpdpbusd(2 * r + 1, reg, 13))
out.append('''	ADDQ $4, SI
	ADDQ $4, R9
	ADDQ $64, DI
	DECQ CX
	JNZ  loop

store:''')
for r in range(12):
    out.append("\tVMOVDQU Y%d, %s(DX)" % (r, str(32 * r) if r else ""))
out.append("\tVZEROUPPER\n\tRET")
print("\n".join(out))
